# Generated by Django 4.0.1 on 2022-11-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='urlFoto',
            field=models.ImageField(upload_to='prendas'),
        ),
    ]
