# Generated by Django 4.0.1 on 2022-11-04 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orden',
            },
        ),
        migrations.CreateModel(
            name='DetalleDeOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.FloatField()),
                ('precio', models.FloatField()),
                ('cantidad', models.FloatField()),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.inventario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.orden')),
            ],
            options={
                'db_table': 'detalleOrden',
                'unique_together': {('orden', 'inventario')},
            },
        ),
    ]
